### ISSUE TITLE
CLI / migrations error with new template

### ISSUE THREAD

**Issue by jodeleeuw** [pushkin-consortium/pushkin-exptemplates-basic#38]
I tried a clean install of version 0.2 of the site template and 5.0 of the experiment template. Running `pushkin prep` threw an error:

![image](https://github.com/pushkin-consortium/pushkin-exptemplates-basic/assets/595524/f65806f5-feb9-408a-82d7-1f3c897319c3)

Digging into the experiment/migrations directory, the file there is:

![image](https://github.com/pushkin-consortium/pushkin-exptemplates-basic/assets/595524/83028177-19a5-4edc-866c-e5764e2da1ff)

I'm guessing the `demo_` prefix is something that should have been updated to match the experiment name (`jspsych7` in my case). I'm not sure where that should have happened.

**Comment by jkhartshorne** [comment]
Did you clean out your docker images first? Usually this happens when you have an existing local database with tables for each experiment created by knex. When you then start a new project, you have new experiments, but knex consults with the database and finds tables for which it can't find migrations files (essentially the knex config) for those tables.

**Comment by jodeleeuw** [comment]
Good call. That was the problem!

**Comment by jkhartshorne** [comment]
We are adding it to the Troubleshooting page in the docs!
